### ISSUE TITLE
Train Deck - Exception no cards

### ISSUE THREAD

**Issue by SeanWalsh95** [SeanWalsh95/Ticket-To-Ride#2]
handle the players having all the cards i.e. what happens when the deck is empty and cannot be reshuffled

**Comment by nm25tunn** [comment]
What will happen is the rebuild deck will return false if it has no discard to rebuild with this may not be a complete solution and we can adapt if need be

**Comment by nm25tunn** [comment]
Someone needs to test this

**Comment by nm25tunn** [comment]
Does not properly repopulate deck.

**Comment by nm25tunn** [comment]
Problem is different now won't let you grab face up cards if the deck is empty

**Comment by SeanWalsh95** [comment]
drawing face up cards if the deck is empty is fixed not sure if we are adding discards back in automatically, leaving the issue open

**Comment by nm25tunn** [comment]
We are adding discards back automatically we are good
