### ISSUE TITLE
Update UML - USE CASE ONLY

### ISSUE THREAD

**Issue by SeanWalsh95** [SeanWalsh95/Ticket-To-Ride#5]
update the UML diagram to fit the current state of the code

~~[This](https://projects.eclipse.org/projects/modeling.umlgen) may prove to be useful~~

THE ONLY UML DIAGRAM REQUIRED IS THE USE CASE DIAGRAM

> "UML USE CASE Diagram is required for HW 5."

**Comment by nm25tunn** [comment]
Jordan completed and uploaded to wiki
